--- 
# Method 1:  you can call the handlers one by one
- hosts: all
  become: true
  tasks:
  - name: Copy index.html
    copy:
     remote_src: yes
     src: /var/www/html/index.html
     dest: /var/www/html/index.html_bkp

  - name: Restart Web Services
    debug:
     msg: Restarting web services
    notify:
    - restart memcached
    - restart apache2
 
# Method 2:  you can call the handlers in one call
  - name: restart everything
    command: echo "this task will restart the web services"
    notify: "restart web services"


# handlers definition
  handlers:
  - name: restart memcached
    service:
     name: memcached
     state: restarted
    listen: "restart web services" # group handlers in one call
  - name: restart apache2
    service:
     name: apache
     state: restarted
    listen: "restart web services"
...
